# Generated by Django 4.0.4 on 2022-04-13 09:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please make an order', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=1, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, help_text='Unikalus užsakymo_ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parduotuve.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalus užsakymo_ID', primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(help_text='product ordered date')),
                ('Customer_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parduotuve.customer')),
                ('Product', models.ManyToManyField(help_text='Choose the correct product for that order', to='parduotuve.product')),
                ('Status_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parduotuve.status')),
            ],
        ),
    ]
